import Head from "next/head";
import Link from "next/link";

import { api } from "@/utils/api";
import { useState } from "react";

export default function Home() {
  console.log("0---");

  const [qwq, setQwq] = useState("---QWQ---");
  const hello = api.example.hello.useQuery({ text: "1" });
  console.log("1---");

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            {hello.data ? hello.data.greeting : "Loading tRPC query..."}
          </h1>
          <button
            onClick={() => {
              console.log("click---");
              setQwq("click!");
            }}
          >{`qaq${qwq}`}</button>
          <Link href="/signin" />
        </div>
      </main>
    </>
  );
}
